title: "Slice & Fire Artisan Pizza"
email: "orders@sliceandfire.example"
description: "Wood-Fired & Hand-Tossed Artisan Pizza. Baked hot in our stone oven."
baseurl: "/Slice-FireArtisanPizza" 
url: "https://khisal786.github.io/"

# Enable Sass processing
sass:
  style: compressed
  sass_dir: _sass

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
